# Generated by Django 4.2.7 on 2023-11-17 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=30, null=True)),
                ('create_in', models.CharField(blank=True, max_length=30, null=True)),
                ('update_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_in', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('qr_code64', models.CharField(blank=True, max_length=6000, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
