# Generated by Django 4.2.7 on 2023-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_update_id_payment_update_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.CharField(blank=True, max_length=50, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
