# Generated by Django 4.2.7 on 2023-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='create_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='update_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
