# Generated by Django 4.2.7 on 2023-11-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_create_in_alter_payment_payment_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_in',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='update_in',
        ),
    ]
