# Generated by Django 4.2.7 on 2023-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_payment_payment_in_remove_payment_update_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='update_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
