# Generated by Django 4.2.7 on 2023-11-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_payment_in_payment_update_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-create_in']},
        ),
    ]
