# Generated by Django 4.2.7 on 2023-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, unique='users', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
