# Generated by Django 4.2.7 on 2023-11-17 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image_user_lat_user_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
