# Generated by Django 4.2.7 on 2023-11-17 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vencimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
