# Generated by Django 4.2.7 on 2023-11-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_vencimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vencimento',
            new_name='expiration',
        ),
    ]
