# Generated by Django 4.2.7 on 2023-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_vencimento_user_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone'),
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
